name: nba-draft
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - jupyter
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - ipykernel
  - selenium
  - beautifulsoup4
  - lxml
  - pip
  - pip: 
      - webdriver-manager
